- name: Ensure docker grafana data directories exist
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ docker_grafana_data_dir }}"
  when: docker_grafana_volumes|length > 0
  tags:
    - install
    - upgrade

- name: Run docker grafana container
  become: true
  docker:
    docker_api_version: "{{ docker_api_version }}"
    env: "{{ docker_grafana_env }}"
    expose: "{{ docker_grafana_expose }}"
    image: "{{ docker_grafana_image }}"
    name: "{{ docker_grafana_name }}"
    ports: "{{ docker_grafana_ports }}"
    links: "{{ docker_grafana_links }}"
    volumes: "{{ docker_grafana_volumes }}"
    memory_limit: "{{ docker_grafana_memory_limit }}"
    log_driver: "{{ docker_grafana_log_driver }}"
    log_opt: "{{ docker_grafana_log_opt }}"
    pull: always
    restart_policy: always
    state: reloaded
  tags:
    - install
    - upgrade
