- name: Ensure docke volume mapping host directories exist
  file:
    state: directory
    path: "{{ item | regex_replace('^(?P<host>.+):(?P<container>.+):(?P<mode>.+)', '\\g<host>') }}"
  with_items:
    - "{{ docker_grafana_directory_volumes }}"
  tags:
    - install
    - upgrade

- name: Ensure docker volume mapping host file directories exist
  file:
    state: directory
    path: "{{ item | regex_replace('^(?P<host>.+):(?P<container>.+):(?P<mode>.+)', '\\g<host>') | dirname }}"
  with_items:
    - "{{ docker_grafana_file_volumes }}"
  tags:
    - install
    - upgrade

- name: Copy docker volume mapping host file
  template:
    src="{{ docker_grafana_template_path }}{{ item | regex_replace('^(?P<host>.+):(?P<container>.+):(?P<mode>.+)', '\\g<host>') | basename }}.j2"
    dest="{{ item | regex_replace('^(?P<host>.+):(?P<container>.+):(?P<mode>.+)', '\\g<host>') }}"
    mode='0644'
  with_items:
    - "{{ docker_grafana_file_volumes }}"
  tags:
    - install
    - upgrade

- name: Remove existing {{ docker_grafana_name }} container
  docker:
    docker_api_version: "{{ docker_api_version }}"
    image: "{{ docker_grafana_image }}"
    name: "{{ docker_grafana_name }}"
    state: absent
  tags:
    - install
    - upgrade

- name: Run docker grafana container
  become: true
  docker:
    docker_api_version: "{{ docker_api_version }}"
    env: "{{ docker_grafana_env }}"
    expose: "{{ docker_grafana_expose }}"
    image: "{{ docker_grafana_image }}"
    name: "{{ docker_grafana_name }}"
    ports: "{{ docker_grafana_ports }}"
    links: "{{ docker_grafana_links }}"
    volumes: "{{ docker_grafana_volumes }}"
    memory_limit: "{{ docker_grafana_memory_limit }}"
    log_driver: "{{ docker_grafana_log_driver }}"
    log_opt: "{{ docker_grafana_log_opt }}"
    pull: always
    restart_policy: always
    state: reloaded
  tags:
    - install
    - upgrade
